### ISSUE TITLE
`method does not override or implement a method from a supertype` Error on RNPaystackPackage.java

### ISSUE THREAD

**Issue by steveamaza** [tolu360/react-native-paystack#2]
On installing the react-native-paystack Library, there is an error I can't seem to get past.

These are the two errors shown on Android Studio

`Error:(16, 5) error: method does not override or implement a method from a supertype`

`Error:Execution failed for task ':react-native-paystack:compileReleaseJavaWithJavac'.
 Compilation failed; see the compiler error output for details.`

Both of these errors seem to emanate from the `createJSModules` function as shown below

```package com.arttitude360.reactnative.rnpaystack;

import ...

public class RNPaystackPackage implements ReactPackage {
    
    @Override     // <--- this module
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();
        modules.add(new RNPaystackModule(reactContext));
        return modules;
    }
}
```
How do I resolve this please 🙂

**Comment by tolu360** [comment]
@steveamaza, if you are working with RN version >= 0.47, please pull in the latest version of this library (3.1.1) - just handled a breaking change introduced in 0.47. 

Clean up your build by running - `cd android && ./gradlew clean` - try to build again. Let me know if the update resolves your issue.

**Comment by steveamaza** [comment]
Thank you! This works. I appreciate
